import { Album } from "../../types/Album.ts";

const SERIES = "THE IDOLM@STER SideM ANIMATION PROJECT";

const AnimationProject: Array<Album> = [
  // ANIMATION PROJECT
  {
    id: "lacm-14671",
    name: `${SERIES} 01 Reason!!`,
    series: SERIES,
    brand: "sidem",
    cover: "https://www.lantis.jp/sidem/releaseinfo/img/jk_AP01.jpg",
    platform: {
      spotify: "2dWuenMwbM25FIFG8K7ACG",
      applemusic: "1656243939",
      amazon: "B0BN8RQL15",
    },
    songs: [
      "Reason!!",
      "流星PARADE",
      "夏時間グラフィティ",
    ],
  },
  {
    id: "lacm-14672",
    name: `${SERIES} 02 TOMORROW DIAMOND`,
    series: SERIES,
    brand: "sidem",
    cover: "https://www.lantis.jp/sidem/releaseinfo/img/jk_AP02.jpg",
    platform: {
      spotify: "1Z04uyUlHNIhMyDveIRpO8",
      applemusic: "1656243994",
      amazon: "B0BN8VGT6W",
    },
    songs: [
      "TOMORROW DIAMOND",
    ],
  },
  {
    id: "lacm-14673",
    name: `${SERIES} 03 From Teacher To Future!`,
    series: SERIES,
    brand: "sidem",
    cover: "https://www.lantis.jp/sidem/releaseinfo/img/jk_AP03.jpg",
    platform: {
      spotify: "5FzHaof7dUEZamIot9wQGu",
      applemusic: "1656386967",
      amazon: "B0BNBYT718",
    },
    songs: [],
  },
  {
    id: "lacm-14674",
    name: `${SERIES} 04 AFTER THE RAIN`,
    series: SERIES,
    brand: "sidem",
    cover: "https://www.lantis.jp/sidem/releaseinfo/img/jk_AP04.jpg",
    platform: {
      spotify: "2fdK6oeaJbSew1PUJkIe4u",
      applemusic: "1656387530",
      amazon: "B0BNBX3DVX",
    },
    songs: [
      "AFTER THE RAIN",
    ],
  },
  {
    id: "lacm-14675",
    name: `${SERIES} 05 Over AGAIN`,
    series: SERIES,
    brand: "sidem",
    cover: "https://www.lantis.jp/sidem/releaseinfo/img/jk_AP05.jpg",
    platform: {
      spotify: "2NPZLYKvehiwx07Y35gslb",
      applemusic: "1656239348",
      amazon: "B0BN8QYPKV",
    },
    songs: [
      "Over AGAIN",
    ],
  },
  {
    id: "lacm-14676",
    name: `${SERIES} 06 Sunset★Colors`,
    series: SERIES,
    brand: "sidem",
    cover: "https://www.lantis.jp/sidem/releaseinfo/img/jk_AP06.jpg",
    platform: {
      spotify: "7s4lwo5mLV47Xd2abyT5yK",
      applemusic: "1656245219",
      amazon: "B0BN8S1DR1",
    },
    songs: [
      "Sunset★Colors",
    ],
  },
  {
    id: "lacm-14677",
    name: `${SERIES} 07 ARRIVE TO STAR`,
    series: SERIES,
    brand: "sidem",
    cover: "https://www.lantis.jp/sidem/releaseinfo/img/jk_AP07.jpg",
    platform: {
      spotify: "21asvj6ocQlnDLJYh7paBY",
      applemusic: "1656244152",
      amazon: "B0BN8Z8779",
    },
    songs: [
      "ARRIVE TO STAR",
    ],
  },
  {
    id: "laca-9571",
    name: `${SERIES} 08 GLORIOUS RO@D`,
    series: SERIES,
    brand: "sidem",
    cover: "https://www.lantis.jp/sidem/releaseinfo/img/jk_AP08.jpg",
    platform: {
      spotify: "3YcpoOnFsqViYonvf5kB7D",
      applemusic: "1658656743",
      amazon: "B0BPFC8LRD",
    },
    songs: [
      "We Are 315!!",
      "一番星の誓い",
      "リスタート",
      "出会いはひょんなことから",
      "生まれた光",
      "人を笑顔にするということ",
      "世界は動き出す",
      "彼らの日常",
      "スタートダッシュ！",
      "デコボコユニット",
      "見慣れた風景",
      "夢を絆に変えて",
      "トホホ…",
      "おかしいな？",
      "ソボクな疑問",
      "不穏",
      "最強のチームワーク",
      "夢に向かって",
      "自慢のアイドル",
      "穏やかな一日",
      "動揺",
      "同じ願いを持つ仲間",
      "あたたかい場所",
      "ポジティブシンキング",
      "青春100パーセント",
      "小さな違和感",
      "トラブル発生",
      "出発進行！",
      "春夏秋冬四季おり",
      "日常は今日も続く",
      "テーブルを囲んで",
      "広まる噂",
      "始まりのこの場所で",
      "信念を胸に",
      "想いをひとつにして",
      "幕を上げよう",
      "さぁ、行こう！この道の先へ",
      "理由ワケあって、アイドル！",
      "パッション！パッション！！",
      "ドタバタコメディ",
      "スキャンダル！？",
      "熱血大陸",
      "二人の旋律",
      "Next Episode",
      "GLORIOUS RO@D",
    ],
  },
];

export default AnimationProject;
