import { Album } from "../../types/Album.ts";

const BestAlbum: Array<Album> = [
  {
    id: "laca-9961",
    name: "THE IDOLM@STER LIVE THE@TER BEST",
    brand: "millionlive",
    series: "THE IDOLM@STER MILLION LIVE! ベストアルバム",
    cover: "https://www.lantis.jp/imas/img/LACA-9961_LACA-9965.png",
    platform: {
      spotify: "0HrUhdNjJ2YoBhUlEwNVt3",
      applemusic: "1677781269",
      amazon: "B0BYNC66X4",
    },
    songs: [
      "Legend Girls!!",
      "PRETTY DREAMER",
      "Blue Symphony",
      "Sentimental Venus",
      "Marionetteは眠らない",
      "カワラナイモノ",
      "Good-Sleep, Baby♡",
      "Helloコンチェルト",
      "瞳の中のシリウス",
      "Fu-Wa-Du-Wa",
      "ココロがかえる場所",
      "Bigバルーン",
      "合言葉はスタートアップ！",
      "Growing Storm!",
      "Shooting Stars",
      "Eternal Harmony",
      "HOME, SWEET FRIENDSHIP",
      "ジレるハートに火をつけて",
      "Birth of Color",
      "ドリームトラベラー",
      "星屑のシンフォニア",
      "STANDING ALIVE",
      "ハルカナミライ",
      "成長Chu→LOVER!!",
      "エスケープ",
      "Eternal Spiral",
      "piece of cake",
      "アライブファクター",
      "Persona Voice",
      "Cut. Cut. Cut.",
      "Smiling Crescent",
      "Decided",
      "深層マーメイド",
      "HELLO, YOUR ANGEL♪",
      "G♡F",
      "little trip around the world",
      "Melody in scape",
      "“Your” HOME TOWN",
      "fruity love",
      "夜に輝く星座のように",
      "秘密のメモリーズ",
      "たしかな足跡",
      "Understand? Understand!",
      "ジャングル☆パーティー",
      "Beat the World!!!",
      "Emergence Vibe",
      "Dreamscape",
      "ランニング・ハイッ",
      "ゲキテキ！ムテキ！恋したい！",
      "Bonnes! Bonnes!! Vacances!!!",
      "NO CURRY NO LIFE",
      "サンリズム・オーケストラ♪",
      "Raise the FLAG",
      "P.S I Love You",
      "プリムラ",
      "待ちぼうけのLacrima",
      "brave HARMONY",
      "リフレインキス",
      "Sweet Sweet Soul",
      "メメント？モメント♪ルルルルル☆",
      "永遠の花",
      "Starry Melody",
    ],
  },
  {
    id: "laca-9966",
    name: "THE IDOLM@STER MILLION THE@TER BEST",
    brand: "millionlive",
    series: "THE IDOLM@STER MILLION LIVE! ベストアルバム",
    cover: "https://www.lantis.jp/imas/img/LACA-9966_LACA-9968.png",
    platform: {
      spotify: "2mX8ucwnOPF7mCFDzTLviH",
      applemusic: "1677585185",
      amazon: "B0BYNFYQRB",
    },
    songs: [
      "FairyTaleじゃいられない",
      "Angelic Parade♪",
      "Princess Be Ambitious!!",
      "昏き星、遠い月",
      "虹色letters",
      "ZETTAI × BREAK!! トゥインクルリズム",
      "Melty Fantasia",
      "花ざかりWeekend✿",
      "咲くは浮世の君花火",
      "ハーモニクス",
      "ハルマチ女子",
      "だってあなたはプリンセス",
      "月曜日のクリームソーダ",
      "ピコピコIIKO! インベーダー",
      "Episode. Tiara",
      "dans l'obscurité",
      "ラビットファー",
      "Cherry Colored Love",
      "Fermata in Rapsodia",
      "百花は月下に散りぬるを",
      "Super Duper",
      "絶対的Performer",
      "Special Wonderful Smile",
      "Parade d’amour",
      "Deep, Deep Blue",
      "Arrive You ～それが運命でも～",
      "Black★Party",
      "深紅のパシオン",
      "ReTale",
      "フリースタイル・トップアイドル！",
      "ABSOLUTE RUN!!!",
      "創造は始まりの風を連れて",
      "俠気乱舞",
      "赤い世界が消える頃",
      "ビッグバンズバリボー!!!!!",
      "オーディナリィ・クローバー",
      "ラスト・アクトレス",
      "Girl meets Wonder",
      "World Changer",
      "クルリウタ",
      "アライアンス・スターダスト",
      "Shine My Way",
      "カーテシーフラワー",
      "聖ミリオン女学園校歌",
      "花びらメモリーズ",
      "U・N・M・E・I ライブ",
      "ターンオンタイム！",
      "ENDLESS TOUR",
    ],
  },
  {
    id: "laca-25043",
    name: "THE IDOLM@STER 765 MILLION ALLSTARS BEST",
    brand: "millionlive",
    series: "THE IDOLM@STER MILLION LIVE! ベストアルバム",
    cover: "https://www.lantis.jp/imas/img/LACA-25043.png",
    platform: {
      spotify: "2mUZGYVQOeOOEpiBK7iiK4",
      applemusic: "1677105366",
      amazon: "B0BYDMVFNN",
    },
    songs: [
      "Thank you! (765 MILLION ALLSTARS ver.)",
      "Welcome!! (765 MILLION ALLSTARS ver.)",
      "Dreaming! (765 MILLION ALLSTARS ver.)",
      "Brand New Theater!",
      "UNION!!",
      "Flyers!!!",
      "Glow map",
      "Harmony 4 you",
      "夢にかけるRainbow (Brand New Ver.)",
      "Crossing!",
    ],
  },
];

export default BestAlbum;
