import { Album } from "../../types/Album.ts";

const MillionTheaterGeneration: Array<Album> = [
  {
    id: "lacm-14631",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 01 Brand New Theater!",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG01_H1_Full.jpg",
    spotify: "1Qf0OVZGtS3qhAYgUPabnW",
    applemusic: "1658285570",
    amazon: "B0BP7SR2RY",
  },
  {
    id: "lacm-14632",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 02 フェアリースターズ",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG02_H1.jpg",
    spotify: "5MpI371XgTIRpGTFSQQie6",
    applemusic: "1658832558",
    amazon: "B0BSB2WLZS",
  },
  {
    id: "lacm-14633",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 03 エンジェルスターズ",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG03_H1.jpg",
    spotify: "1BisYJhb9AdegHtlFZ3fl1",
    applemusic: "1658305128",
    amazon: "B0BP832DN6",
  },
  {
    id: "lacm-14634",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 04 プリンセススターズ",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG04_H1.jpg",
    spotify: "6k4Ee74mBhYsamQQ3iuumR",
    applemusic: "1658305081",
    amazon: "B0BP84T73Y",
  },
  {
    id: "lacm-14635",
    name:
      "THE IDOLM@STER MILLION THE@TER GENERATION 05 夜想令嬢 -GRAC&E NOCTURNE-",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG05_H1.jpg",
    spotify: "4Jpd3nBH6a3FZBcZCigTJh",
    applemusic: "1658304396",
    amazon: "B0BP82V7MX",
  },
  {
    id: "lacm-14636",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 06 Cleasky",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG06_H1.jpg",
    spotify: "00KZ35DyzALroEalMDTVmh",
    applemusic: "1658304238",
    amazon: "B0BP7ZR5DL",
  },
  {
    id: "lacm-14637",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 07 トゥインクルリズム",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG07_H1.jpg",
    spotify: "463LWhdjR3Q122CTaKU7qx",
    applemusic: "1658303831",
    amazon: "B0BP8D5B2B",
  },
  {
    id: "lacm-14638",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 08 EScape",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG08_H1.jpg",
    spotify: "6Gy0t8MgPIC4GMZcYX3hIa",
    applemusic: "1658307181",
    amazon: "B0BP85NJ4M",
  },
  {
    id: "lacm-14639",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 09 4Luxury",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG09_H1.jpg",
    spotify: "4hIm4rGzPU1YbQ88jmwirA",
    applemusic: "1658304346",
    amazon: "B0BP81K7N1",
  },
  {
    id: "lacm-14640",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 10 閃光 HANABI団",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG10_H1.jpg",
    spotify: "3yMOG8hVXOI4DRrUixNXBE",
    applemusic: "1658305736",
    amazon: "B0BP85YLMM",
  },
  {
    id: "lacm-14641",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 11 UNION!!",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG11_H1.jpg",
    spotify: "3aCN43uJ8NWwNbxQuKkcSt",
    applemusic: "1658306238",
    amazon: "B0BP828XKZ",
  },
  {
    id: "lacm-14642",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 12 D/Zeal",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG12_H1.jpg",
    spotify: "18rvG8u4mjj3BV0g3Fwm17",
    applemusic: "1658303353",
    amazon: "B0BP83CTTZ",
  },
  {
    id: "lacm-14823",
    name:
      "THE IDOLM@STER MILLION THE@TER GENERATION 13 りるきゃん ~3 little candy~",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG13_H1.jpg",
    spotify: "5qa2bHCRgdrocEpiWWLbxx",
    applemusic: "1658303220",
    amazon: "B0BP83R2QH",
  },
  {
    id: "lacm-14824",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 14 Charlotte・Charlotte",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG14_H1.jpg",
    spotify: "3Fbpi07fJnHysSlDTVkurF",
    applemusic: "1658303898",
    amazon: "B0BP878NBJ",
  },
  {
    id: "lacm-14825",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 15 Jelly PoP Beans",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG15_H1.jpg",
    spotify: "0aF69rLzzjsSOJzErPvdAQ",
    applemusic: "1658306252",
    amazon: "B0BP83BG87",
  },
  {
    id: "lacm-14826",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 16 ピコピコプラネッツ",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG16_H1.jpg",
    spotify: "1rHmz6BsIpcz7fA463NqUM",
    applemusic: "1658303734",
    amazon: "B0BP81B23D",
  },
  {
    id: "lacm-14827",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 17 STAR ELEMENTS",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG17_H1.jpg",
    spotify: "5hcxMJUIeeZtHQSASinlO4",
    applemusic: "1658306293",
    amazon: "B0BP83YD2X",
  },
  {
    id: "lacm-14828",
    name: "THE IDOLM@STER MILLION THE@TER GENERATION 18 765PRO ALLSTARS",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTG18_H1.jpg",
    spotify: "7iwI8fznwZNrH8DM6mxZQm",
    applemusic: "1658199687",
    amazon: "B0BP5JHJXF",
  },
];

export default MillionTheaterGeneration;
