import { Album } from "../../types/Album.ts";

const MillionTheaterWave: Array<Album> = [
  {
    id: "lacm-14891",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 01 Flyers!!!",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW01_H1.jpg",
    spotify: "3XMVnavGGMGhtKL5kX9wSq",
    applemusic: undefined,
    amazon: "B0BP721ZTT",
  },
  {
    id: "lacm-14892",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 02 Chrono-Lexica",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW02_H1.jpg",
    spotify: "0n1EdkiGkULdbdAbcj3FI3",
    applemusic: "1658222656",
    amazon: "B0BP6FSQV8",
  },
  {
    id: "lacm-14893",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 03 Xs",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW03_H1.jpg",
    spotify: "6bRm5kHYUxrQIsLhVUn5oX",
    applemusic: "1658222337",
    amazon: "B0BP68DNLF",
  },
  {
    id: "lacm-14894",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 04 Sherry'n Cherry",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW04_H1.jpg",
    spotify: "5XJU5PcncxC8kuLr0uZ35w",
    applemusic: "1658221508",
    amazon: "B0BP65X211",
  },
  {
    id: "lacm-14895",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 05 ARCANA",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW05_H1.jpg",
    spotify: "6dPf4D4ahsUrXfXacWhKNu",
    applemusic: "1660061660",
    amazon: "B0BP62SZXZ",
  },
  {
    id: "lacm-14896",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 06 花咲夜",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW06_H1.jpg",
    spotify: "4to4QXWpdanY8GmKkcKX8H",
    applemusic: "1658224005",
    amazon: "B0BP6C8RD6",
  },
  {
    id: "lacm-14897",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 07 Jus-2-Mint",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW07_H1.jpg",
    spotify: "7mihuPl9XKNe5EbrWmf9Gs",
    applemusic: "1658224353",
    amazon: "B0BP6HHNB5",
  },
  {
    id: "lacm-14898",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 08 miraclesonic★expassion",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW08_H1.jpg",
    spotify: "1dOIaP2WYutQKZ8fWFaXi8",
    applemusic: "1658224826",
    amazon: "B0BS9ZLQXM",
  },
  {
    id: "lacm-14899",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 09 Fleuranges",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW09_H1.jpg",
    spotify: "5dRsYjOUip5UV88wKPAuGJ",
    applemusic: "1658261696",
    amazon: "B0BP7JNN76",
  },
  {
    id: "lacm-14900",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 10 Glow Map",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW10_H1.jpg",
    spotify: "0i8lhN2S9zPhErVX2LXhc0",
    applemusic: "1658262664",
    amazon: "B0BP7GXTMV",
  },
  {
    id: "lacm-14901",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 11 オペラセリア・煌輝座",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW11_H1.jpg",
    spotify: "2SSr71xZDj52IgJ3zacjfx",
    applemusic: "1658265137",
    amazon: "B0BP7NJKXT",
  },
  {
    id: "lacm-14902",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 12 ダイヤモンドダイバー◇",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW12_H1.jpg",
    spotify: "6raoTree2kzuHvxAfcjkNt",
    applemusic: "1658269690",
    amazon: "B0BP7QHZBQ",
  },
  {
    id: "lacm-14903",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 13 TIntMe!",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW13_H1.jpg",
    spotify: "5ug6ELg787KuXMs1Z5gthX",
    applemusic: "1658270176",
    amazon: "B0BP7N7BVC",
  },
  {
    id: "lacm-14904",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 14 TRICK&TREAT",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW14_H1.jpg",
    spotify: "54oac3e7RYyha5LkSKABsA",
    applemusic: "1658270027",
    amazon: "B0BP7QGLR5",
  },
  {
    id: "lacm-14905",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 15 chicAAmor",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW15_H1.jpg",
    spotify: "2EQQNrat2zwQMfwD67OycQ",
    applemusic: "1658341292",
    amazon: "B0BP8C7TDC",
  },
  {
    id: "lacm-24106",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 16 ≡君彩≡",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW16_H1.jpg",
    spotify: "5HGLbVSNqj9HQHGGYe39No",
    applemusic: "1658261376",
    amazon: "B0BP7JZV59",
  },
  {
    id: "lacm-24107",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 17 ARMooo",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW17_H1.jpg",
    spotify: "6SYVfAsmO3ctaLBZbMlEhs",
    applemusic: "1658262860",
    amazon: "B0BP7GYQBX",
  },
  {
    id: "lacm-24108",
    name: "THE IDOLM@STER MILLION THE@TER WAVE 18 ストロベリーポップムーン",
    series: "millionlive",
    cover: "https://www.lantis.jp/imas/img/MTW18_H1.jpg",
    spotify: "2h7qFCIuwpnamJlTOgS7CU",
    applemusic: "1658341924",
    amazon: "B0BP94HTTS",
  },
];

export default MillionTheaterWave;
